"""empty message

Revision ID: dd53bfb57977
Revises: 
Create Date: 2021-12-22 12:33:22.201663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd53bfb57977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('contact', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact', 'user', ['user_id'], ['id'])
    op.add_column('task', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_timestamp'), 'task', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_timestamp'), table_name='task')
    op.drop_column('task', 'user_id')
    op.drop_column('task', 'timestamp')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'user_id')
    op.drop_column('contact', 'timestamp')
    # ### end Alembic commands ###
